### PR TITLE
Fixed compilation errors for GHC-9.0.1

### PR DESCRIPTION
**Pull request by jchia**
I'm not sure why the `MonadIO m` constraint for the `Taffy` type synonym was needed; it didn't seem necessary to me, but there were compilation errors until I removed it.

The other changes, related to eta-expansion in association with implicit-param functions, are necessary because of simplified subsumption in GHC 9.0.1. https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#compiler-changes

### CODE REVIEW

**Comment by IvanMalison** [comment]
Thanks! I'll take a look at this asap!

**Comment by jchia** [comment]
To actually build with GHC 9.0.1 using stack, I had to change stack.yaml as I did in this [branch](https://github.com/jchia/taffybar/tree/ghc-9-full), but changing stack.yaml is a matter for another commit, not this one.

**Comment by cumber** [comment]
Any chance we could get hackage release with this PR merged? It's preventing taffybar from working out of the box from nixpkgs.

**Comment by IvanMalison** [comment]
@cumber yep been meaning to get to this.
