### ISSUE TITLE
Upower IDL files can't be parsed by haskell-dbus version 1.1.1 becasue of annotation properties

### ISSUE THREAD

**Issue by LeifW** [taffybar/taffybar#427]
**Describe the bug**
Trying to build on GHC 8.6: it gets to here and then fails:
```
[ 3 of 61] Compiling System.Taffybar.DBus.Client.UPowerDevice ( src/System/Taffybar/DBus/Client/UPowerDevice.hs, dist/build/System/Taffybar/DBus/Client/UPowerDevice.dyn_o )

src/System/Taffybar/DBus/Client/UPowerDevice.hs:1:1: error:
    Exception when trying to run compile-time code:
      Prelude.head: empty list
    Code: generateClientFromFile
            defaultRecordGenerationParams
              {recordName = Just "BatteryInfo", recordPrefix = "battery",
               recordTypeForName = batteryTypeForName}
            uPowerGenerationParams
            False
            $ "dbus-xml" </> "org.freedesktop.UPower.Device.xml"
  |
1 | {-# LANGUAGE TemplateHaskell #-}
  | ^
[ 4 of 61] Compiling System.Taffybar.DBus.Client.UPower ( src/System/Taffybar/DBus/Client/UPower.hs, dist/build/System/Taffybar/DBus/Client/UPower.dyn_o )

src/System/Taffybar/DBus/Client/UPower.hs:1:1: error:
    Exception when trying to run compile-time code:
      Prelude.head: empty list
    Code: generateClientFromFile
            defaultRecordGenerationParams
              {recordName = Just "UPowerInfo", recordPrefix = "upi"}
            uPowerGenerationParams {genObjectPath = Just uPowerBaseObjectPath}
            False
            $ "dbus-xml" </> "org.freedesktop.UPower.xml"
  |
1 | {-# LANGUAGE TemplateHaskell #-}
  | ^
[ 5 of 61] Compiling System.Taffybar.DBus.Client.MPRIS2 ( src/System/Taffybar/DBus/Client/MPRIS2.hs, dist/build/System/Taffybar/DBus/Client/MPRIS2.dyn_o )
```

**To Reproduce**
Clone the taffybar repo, and then run "cabal configure; cabal build" in there.
**Expected behavior**
The build succeeds

**Version information**
Taffybar current release (3.0.0) or git master (d65b3997fe6203b8ca13854238f9a2a00363b2ec)
Deps installed as Arch packages
Gtk version:
gtk3 3.24.1+8+g220f77d8c1-1

**Comment by IvanMalison** [comment]
What version of haskell-dbus?

**Comment by LeifW** [comment]
1.1.1

**Comment by IvanMalison** [comment]
@LeifW I think this issue is most likely to have to do with that than with anything with ghc8.6

**Comment by IvanMalison** [comment]
Could also be related to something about how template haskell is processed though. That list should not be empty though,

**Comment by IvanMalison** [comment]
I suspect that this would not happen with a stack build because it would use the older haskell-dbus. Can you confirm?

**Comment by rblaze** [comment]
I'm pretty sure I had seen this crash and fixed it. Could you share that xml file with me?

**Comment by IvanMalison** [comment]
Looks like it is these:
https://github.com/taffybar/taffybar/blob/master/dbus-xml/org.freedesktop.UPower.Device.xml
https://github.com/taffybar/taffybar/blob/master/dbus-xml/org.freedesktop.UPower.xml

**Comment by rblaze** [comment]
Ok, I fixed it indeed, but did not release new version yet.

Workaround: drop "annotation" tags from IDL. It is ignored anyway, and current release can't parse it. I'll release dbus-1.1.2 with latest fixes.

Just to make sure, could you try building with HEAD? I think stack allows to override package version with the one from git repo.

**Comment by IvanMalison** [comment]
@rblaze Yep, its not hard. will do in a sec.

**Comment by IvanMalison** [comment]
@LeifW so as I suspected the issue is actually with haskell-dbus and not with ghc. Can you confirm?

**Comment by IvanMalison** [comment]
@rblaze 1.2.1 does fix the issue, but we get other compilation probelms with status-notifier-item because of changes to types, so we cant bump taffybars version. Things are fine if we stay at 1.0.1. Unfortunately, because of the way that arch-linux sets things up, I'm not sure arch users will be able to downgrade. Perhaps @LeifW can comment about the best way to proceed.

**Comment by LeifW** [comment]
Yeah, sorry if I implied this was a GHC 8.6 thing in my report. I've used taffybar with 8.6 before - the pertinent difference now is that the dbus library got upgraded. I think I'd prefer change status-notifier-item to build with the new dbus version. I put up a PR for that: https://github.com/IvanMalison/status-notifier-item/pull/3 The dbus library is in the official repos, and seem loath to downgrade things.
After those changes, dbus 1.2.1 and taffybar work great for me. Thanks!

**Comment by IvanMalison** [comment]
@rblaze Hmm changing the type of the interface like this has actually broken ( previously working) the cabal install command for taffybar.

I know that it was a small change, but you should consider a major version bump for dbus when you do something like that that changes the types of the exposed api. There is actually an upper version bound on dbus in the cabal file of taffybar (https://github.com/travitch/taffybar/blob/d49e8dfa229b42e654bc18f4801aff061919c751/taffybar.cabal#L49) but it did not exclude this change bc it was not a major version bump.

**Comment by IvanMalison** [comment]
This is fixed by the new version of status-notifier-item
